config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :authentication, path: "", as: "" do
    resources :users, only: %i[ new create ], path: "/register", path_names: { new: "/" }
    resources :sessions, only: %i[ new create destroy ], path: "/login", path_names: { new: "/" }
  end

  resources :favorites, only: %i[ index create destroy ], param: :product_id
  resources :shopping_carts, only: %i[ index create destroy update ], param: :product_id
  resources :users, only: %i[ show edit update ], path: "/user", param: :username
  resources :categories, except: :show
  resources :products, path: "/"
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  def index
    @pagy, @products = pagy_countless(FindProducts.new.call({ shopping_cart: true }).load_async, limit: 12)
  end

  def create
    if product.shopping_cart.present?
      product.shopping_cart.update(amount: product.shopping_cart.amount + 1)
    else
      product.shopping_carts.create(user: Current.user, amount: 1)
    end

    redirect_to product_path(product.id), notice: t(".created")
  end

  def update
    if shopping_cart_params[:amount].to_i > 0
      product.shopping_cart.update(shopping_cart_params)
    end
  end

  def destroy
    product.shopping_cart.destroy
    redirect_to shopping_carts_path, notice: t(".destroyed"), status: :see_other
  end

  private

  def product
    @product ||= Product.find(params[:product_id])
  end

  def shopping_cart_params
    params.permit(:amount)
  end
end

app/views/shopping_carts/_product.html.erb
<section class="border-2 border-gray-300 rounded-xl flex gap-3 relative my-4 p-4 max-w-2xl mx-3 sm:mx-auto">
  <!-- <%= link_to product_path(product.id), class: "product flex gap-5", "data-turbo-frame": "_top" do %> -->
    <%= image_tag product.photo.attached? ? product.photo : "placeholder.jpg", class: "max-w-32 rounded" %>
    <div>
      <h2 class="font-bold mb-2"><%= product.title %></h2>
      <span class="font-semibold">$ <%= product.price %> c/u</span>
      <div class="flex gap-4 mt-2">
        <%= form_with url: shopping_cart_path(product.id), method: :patch, class: "flex items-center gap-2" do |form| %>
          <!-- <%= form.label :amount %> -->
          <%= form.number_field :amount, value: "#{product.shopping_cart.amount}", min: 1, class: "w-20 p-1 text-center rounded-2xl border-2 border-gray-300" %>
    
          <%= form.submit t('.update'), class: "flex items-center justify-center px-2 h-9 rounded-3xl bg-main-color text-white font-semibold active:scale-90 duration-300" %>
        <% end %>
    
        <%= link_to shopping_cart_path(product.id), data: { turbo_method: :delete, turbo_confirm: t('common.confirm') }, class: "Btn flex items-center justify-start w-9 h-9 border-none rounded-full cursor-pointer overflow-hidden duration-300 shadow bg-red-600 sm:hover:w-32 hover:rounded-3xl active:scale-90 relative" do %>
          <%= image_tag "icons/trash.svg", class: "w-full p-2 transition-all duration-300 flex items-center justify-center sign" %>
          <p class="absolute right-0 w-0 opacity-0 text-white font-semibold transition-all duration-300 text hidden sm:block">Remove</p>
        <% end %>
      </div>
    </div>
  <!-- <% end %> -->
</section>

<style>
  .Btn:hover .sign {
    width: 40%;
    transition-duration: .3s;
    padding-left: 20px;
  }
  /* hover effect button's text */
  .Btn:hover .text {
    opacity: 1;
    width: 65%;
    transition-duration: .3s;
    padding-right: 10px;
  }

  input[type=number]::-webkit-inner-spin-button, 
  input[type=number]::-webkit-outer-spin-button {
      -webkit-appearance: none;
  }

  input[type=number] {
      -moz-appearance: textfield; /* Para Firefox */
  }
</style>

app/views/shopping_carts/index.html.erb
<h2 class="text-3xl font-bold"><%= t('.title') %></h2>

<%= turbo_frame_tag :products do %>
  <%= turbo_frame_tag "products-#{@pagy.page}", class: "products" do %>
    <%= render partial: "product", collection: @products %>
    <%= turbo_frame_tag "products-#{@pagy.next}", class: "products", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
  <% end %>
<% end %>