config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :authentication, path: "", as: "" do
    resources :users, only: %i[ new create ], path: "/register", path_names: { new: "/" }
    resources :sessions, only: %i[ new create destroy ], path: "/login", path_names: { new: "/" }
  end

  resources :favorites, only: %i[ index create destroy ], param: :product_id
  resources :shopping_carts, only: %i[ index create destroy update ], param: :product_id
  resources :users, only: %i[ show edit update ], path: "/user", param: :username
  resources :categories, except: :show
  resources :products, path: "/"
end

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="flex flex-wrap lg:flex-nowrap justify-between py-4 sm:px-[10%] fixed w-screen backdrop-blur-md z-20" data-controller="menu">
  <%= link_to products_path, class: "text-3xl font-bold text-main-color flex items-center" do %>
    <h1><%= t('app_title') %></h1>
  <% end %>

  <input type="checkbox" id="checkbox" data-action="click->menu#toggle" class="hidden">
  <label for="checkbox" class="toggle lg:hidden relative w-8 h-7 cursor-pointer flex flex-col items-center justify-center gap-2 duration-500">
    <div class="bars bg-black" id="bar1"></div>
    <div class="bars bg-black" id="bar2"></div>
    <div class="bars bg-black" id="bar3"></div>
  </label>

  <section class="items-center gap-4 hidden lg:flex">
    <%= render partial: "shared/items" %>
  </section>

  <!-- Menu mobile -->
  <section class="flex lg:hidden justify-center z-10 h-0 items-center w-full flex-col min-w-[35%] ease-in-out duration-200 -translate-y-48" data-menu-target="items">
    <%= render partial: "shared/items" %>
  </section>
</header>

<style>
  .bars {
    width: 100%;
    height: 3px;
    border-radius: 4px;
  }

  #bar2 {
    transition-duration: .8s;
  }

  #bar1,#bar3 {
    width: 70%;
  }

  #checkbox:checked + .toggle .bars {
    position: absolute;
    transition-duration: .5s;
  }

  #checkbox:checked + .toggle #bar2 {
    transform: scaleX(0);
    transition-duration: .5s;
  }

  #checkbox:checked + .toggle #bar1 {
    width: 100%;
    transform: rotate(45deg);
    transition-duration: .5s;
  }

  #checkbox:checked + .toggle #bar3 {
    width: 100%;
    transform: rotate(-45deg);
    transition-duration: .5s;
  }

  #checkbox:checked + .toggle {
    transition-duration: .5s;
    transform: rotate(180deg);
  }
</style>

app/views/shared/_items.html.erb
<%= link_to t('.add_product'), new_product_path, class: "font-semibold text-xl" if Current.user %>
<%= link_to t('.categories'), categories_path, class: "font-semibold text-xl", data: { turbo_frame: "modal" } if Current.user&.admin? %>
<%= link_to t('.sign_in'), new_session_path, class: "font-semibold text-xl" unless Current.user %>
<%= link_to t('.sign_up'), new_user_path, class: "font-semibold text-xl" unless Current.user %>
<%= link_to t('.logout'), session_path(Current.user.id), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm')
}, class: "font-semibold text-xl" if Current.user %>
<div class="flex gap-2 mt-2 lg:mt-0">
  <%= link_to "#{image_tag "icons/profile.svg", alt: "My profile", class: "w-6 h-6"}".html_safe, user_path(Current.user.username), class: "bg-main-color text-white flex justify-center items-center rounded-full p-2 hover:bg-main-color/90 active:scale-90 duration-500" if Current.user %>
  <%= link_to "#{image_tag "icons/favorite.svg", alt: "My favorites", class: "w-6 h-6"}".html_safe, favorites_path, class: "bg-main-color text-white flex justify-center items-center rounded-full p-2 hover:bg-main-color/90 active:scale-90 duration-500" if Current.user %>
  <%= link_to "#{image_tag "icons/shopping-cart.svg", alt: "Shopping cart", class: "w-6 h-6"}".html_safe, shopping_carts_path, class: "bg-main-color text-white flex justify-center items-center rounded-full p-2 hover:bg-main-color/90 active:scale-90 duration-500" if Current.user %>
</div>