config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :authentication, path: "", as: "" do
    resources :users, only: %i[ new create ], path: "/register", path_names: { new: "/" }
    resources :sessions, only: %i[ new create destroy ], path: "/login", path_names: { new: "/" }
  end

  resources :favorites, only: %i[ index create destroy ], param: :product_id
  resources :shopping_carts, only: %i[ index create destroy update ], param: :product_id
  resources :users, only: %i[ show edit update ], path: "/user", param: :username
  resources :categories, except: :show
  resources :products, path: "/"
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable

  pg_search_scope :search_full_text, against: { title: "A", description: "B" }

  ORDER_BY = {
    expensive: "price DESC",
    cheapest: "price ASC",
    newest: "created_at DESC",
    oldest: "created_at ASC"
  }

  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :price, presence: true

  belongs_to :category
  belongs_to :user, default: -> { Current.user }
  has_many :favorites, dependent: :destroy
  has_many :shopping_carts, dependent: :destroy

  def owner?
    user_id == Current.user&.id
  end

  # Found the user asosiated to shopping cart
  def shopping_cart
    shopping_carts.find_by(user: Current.user)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  skip_before_action :protect_pages, only: %i[ index show ]

  def index
    @categories = Category.order(name: :asc).load_async

    @pagy, @products = pagy_countless(FindProducts.new.call(filter_params).load_async, limit: 12)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product.id), notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize! @product
  end

  def update
    authorize! @product
    if @product.update(product_params)
      redirect_to product_path(@product.id), notice: t(".updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! @product
    @product.destroy

    redirect_to products_path, status: :see_other, notice: t(".destroyed")
  end

  private

  def set_product
    @product ||= Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :stock, :photo, :category_id)
  end

  def filter_params
    params.permit(:query_text, :min_price, :max_price, :order_by, :page, :favorites, :user_id, :category_id)
  end
end

app/views/products/_favorite.html.erb
<div id="<%= "favorite-#{product.id}" %>">
  <% if product.favorite %>
    <%= link_to "#{image_tag "icons/favorite.svg", tag: "Add to favorites", class: "w-10 h-10 bg-main-color text-white flex justify-center items-center rounded-full p-2 hover:bg-main-color/90 active:scale-90 duration-500"}".html_safe, favorite_path(product.id), data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to "#{image_tag "icons/unfavorite.svg", tag: "Remove to favorites", class: "w-10 h-10 bg-main-color text-white flex justify-center items-center rounded-full p-2 hover:bg-main-color/90 active:scale-90 duration-500"}".html_safe, favorites_path(product_id: product.id), data: { turbo_method: :post } %>
  <% end %>  
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div class="flex flex-col gap-1 min-w-72">
    <%= form.label :title, class: "font-semibold" %>
    <%= form.text_field :title, class: "rounded-2xl border-2 focus:border-main-color" %>
  </div>

  <div class="flex flex-col gap-1 min-w-72">
    <%= form.label :description, class: "font-semibold" %>
    <%= form.text_area :description, class: "rounded-2xl border-2 focus:border-main-color" %>
  </div>

  <div class="flex flex-col gap-1 min-w-72">
    <%= form.label :price, class: "font-semibold" %>
    <%= form.number_field :price, class: "rounded-2xl border-2 focus:border-main-color" %>
  </div>

  <div class="flex flex-col gap-1 min-w-72">
    <%= form.label :stock, class: "font-semibold" %>
    <%= form.number_field :stock, class: "rounded-2xl border-2 focus:border-main-color" %>
  </div>

  <div class="flex flex-col gap-1 min-w-72">
    <%= form.label :category_id, class: "font-semibold" %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, class: "rounded-2xl border-2 focus:border-main-color" %>
  </div>

  <div class="flex flex-col gap-1 min-w-72">
    <%= form.label :photo, class: "font-semibold" %>
    <%= form.file_field :photo, class: "rounded-2xl border-2 focus:border-main-color" %>
  </div>

  <div>
    <%= form.submit class: "bg-main-color text-white px-2 py-2 rounded-2xl mt-4 w-full" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<section class="p-5 border-2 hover:border-main-color/50 hover:shadow-zinc-50 w-5/6 sm:w-[calc(50%_-_.5rem)] md:w-[calc(33.33333%_-_.7rem)] lg:w-[calc(25%_-_.9rem)] h-auto rounded-xl">
  <%= link_to product_path(product.id), class: "product", "data-turbo-frame": "_top" do %>
    <%= image_tag product.photo.attached? ? product.photo : "placeholder.jpg", class: "w-full rounded" %>
    <div class="flex justify-between mt-3">
      <h2 class="font-semibold hover:text-main-color"><%= product.title %></h2>
      <span class="text-black/50"><%= product.category.name %></span>
    </div>
  <% end %>
  <div class="flex justify-between items-center">
    <span>$ <%= product.price %></span>
    <%= render partial: "favorite", locals: { product: product } %>
  </div>
</section>

app/views/products/edit.html.erb
<section class="w-full h-[90vh] flex flex-col justify-center items-center">
  <h2 class="text-3xl font-bold mb-4"><%= t('.title') %></h2>

  <%= render "form" %>
</section>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full rounded-xl my-2 border-gray-400" %>
    <div class="flex gap-1 sm:gap-2 md:gap-4">
      <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price], class: "w-1/3 rounded-xl border-gray-400" %>
      <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price], class: "w-1/3 rounded-xl border-gray-400" %>
      <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [ t(".#{order}"), order ] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()', class: "w-1/3 rounded-xl border-gray-400 text-gray-500" } %>
    </div>
  <% end %>

  <div class="my-4 flex gap-2 overflow-auto">
    <%= render(CategoryComponent.new) %>

    <%= render(CategoryComponent.with_collection(@categories)) %>
  </div>

  <%= turbo_frame_tag :products, class: "" do %>
    <%= turbo_frame_tag "products-#{@pagy.page}", class: "products flex flex-col justify-center items-center gap-4 sm:flex-row sm:flex-wrap" do %>
      <%= render partial: "product", collection: @products %>
      <%= turbo_frame_tag "products-#{@pagy.next}", class: "products flex flex-col justify-center items-center gap-4 sm:flex-row sm:flex-wrap", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<section class="w-full h-[90vh] flex flex-col justify-center items-center">
  <h2 class="text-main-color text-5xl font-bold mb-4"><%= t('.title') %></h2>

  <%= render "form" %> 
</section>

app/views/products/show.html.erb
<section class="mx-auto border-2 p-5 flex flex-col rounded-2xl sm:flex-row sm:gap-4 max-w-md sm:max-w-5xl">
  <div>
    <%= image_tag @product.photo.attached? ? @product.photo : "placeholder.jpg", class: "w-full rounded max-w-sm" %>
  </div>

  <div class="mt-5 sm:mt-0 flex flex-col">
    <h2 class="title font-bold text-xl mb-2"><%= @product.title %></h2>
    <p class="description text-black/80"><%= @product.description %></p>

    <div class="flex flex-col sm:flex-row sm:gap-1 md:gap-3">
      <div class="flex items-center justify-between my-2 sm:gap-2 md:gap-4">
        <span class="price">$ <%= @product.price %></span>
        <span>stock: <%= @product.stock %></span>
      </div>

      <div class="flex justify-between items-center mb-2 sm:gap-2 md:gap-4">
        <%= render partial: "favorite", locals: { product: @product } %>
        <%= link_to shopping_carts_path(product_id: @product.id), data: { turbo_method: :post }, class: "CartBtn bg-main-color w-36 h-10 rounded-xl border-none flex items-center cursor-pointer duration-500 overflow-hidden shadow relative text-white font-semibold active:scale-95" do %>
          <%= image_tag "icons/add-shopping-cart.svg", class: "IconContainer absolute left-[-50px] w-7 h-7 bg-transparent rounded-2xl flex items-center justify-center overflow-hidden z-10 duration-500" %>
          <p class="h-full w-full flex items-center justify-center z-[5] duration-500 text">Add to cart</p>
        <% end %>
      </div>
    </div>

    <div>
      <%= link_to t('.show_more', username: @product.user.username), user_path(@product.user.username), class: "italic text-base text-main-color/60 hover:underline" %>
      <%= link_to t('.edit'), edit_product_path(@product.id) if @product.owner? %>
      <%= link_to t('.delete'), product_path(@product.id), data: {
        turbo_method: :delete,
        turbo_confirm: t('common.confirm')
      } if @product.owner? %>
    </div>
  </div>
</section>

<style>
  .CartBtn:hover .IconContainer {
    transform: translateX(58px);
    border-radius: 40px;
    transition-duration: .5s;
  }

  .CartBtn:hover .text {
    transform: translate(10px,0px);
    transition-duration: .5s;
  }
</style>